"""mdo/structures.py — differentiable structural screens for the chamber shell.

NASA SP-8087, *Liquid Rocket Engine Fluid-Cooled Combustion Chambers* (1973;
``propulsion_texts/19730022965.pdf``) §2.1.3 names exactly three structural jobs
for chamber reinforcement:

    "The three areas of structural concern are the hoop support about the
    combustion chamber, the support at the nozzle throat to resist bending and
    buckling, and hoop support about the expansion nozzle to resist collapse
    from hoop compression.  The last condition occurs during operation at sea
    level, where jet separation occurs during start and shutdown and the nozzle
    runs overexpanded during steady-state operation."

Until now the repository screened none of them at the MDO level:

1. **Chamber hoop support** — now covered by the SP-125 p.109 outer-shell hoop
   sizing in :func:`raosim.mdo.mass.closeout_thickness`.
2. **Nozzle collapse under overexpansion** — this module.
3. **Throat bending/buckling support** — this module (reported; see the caveat
   in :func:`throat_support_margin`).

SP-8120, *Liquid Rocket Engine Nozzles* (1977;
``propulsion_texts/19770009165.pdf``) §2.2 records the consequence of missing
(2): *"Nozzle structural failures often are due to inaccurate predictions of the
gas expansion produced by the nozzle.  A typical failure of this kind is the
collapse of the nozzle from overexpansion during ground testing or from high
side loads generated by severe accelerations of the exhaust gas resulting from
unsteady, asymmetric separation of the expanding gases from the nozzle wall."*
SP-8120 cites NASA SP-8007 (*Buckling of Thin-Walled Circular Cylinders*) and
SP-8019 (*Buckling of Thin-Walled Truncated Cones*) as the governing buckling
monographs; those are not in the local corpus, so SP-8007's criteria are
reproduced here from the NASA Technical Reports Server copy of the August 1968
revision (NTRS 19690013955), §4.2.3.

Relationship to the separation constraint
-----------------------------------------
This is *not* a duplicate of ``separation_margin``.  Separation asks whether the
flow detaches; collapse asks whether the shell survives the external pressure it
sees while it is attached and overexpanded.  A nozzle can pass the separation
screen and still be crushed — SP-8087 is explicit that the overexpanded
steady-state condition is the design case, not just the start/shutdown transient.
"""

from __future__ import annotations

from typing import NamedTuple

import jax.numpy as jnp
from jax import Array

from raosim.mdo.grid import StationGrid
from raosim.mdo.schema import MissionSpec

__all__ = [
    "NozzleCollapseScreen",
    "nozzle_collapse_screen",
    "SP8007_EXTERNAL_PRESSURE",
    "SP8087_REINFORCEMENT",
    "SP8120_OVEREXPANSION_COLLAPSE",
]

SP8007_EXTERNAL_PRESSURE = (
    "NASA SP-8007 rev. Aug 1968 sec. 4.2.3 eqs. (16)-(21) "
    "(external-pressure buckling of thin-walled circular cylinders)"
)
SP8087_REINFORCEMENT = (
    "NASA SP-8087 sec. 2.1.3 (chamber reinforcement; nozzle hoop-compression "
    "collapse at sea level)"
)
SP8120_OVEREXPANSION_COLLAPSE = (
    "NASA SP-8120 sec. 2.2 (nozzle collapse from overexpansion in ground test)"
)


class NozzleCollapseScreen(NamedTuple):
    """External-pressure collapse screen over the divergent shell."""

    external_dp: Array          # (n,) max(p_ambient - p_gas, 0) [Pa]
    critical_pressure: Array    # (n,) allowable external pressure [Pa]
    margin_profile: Array       # (n,) p_cr/FoS - dp  [Pa], >= 0 is safe
    margin: Array               # scalar governing margin [Pa]
    normalized_margin: Array    # scalar margin / max(dp) [-], scale-free
    equivalent_radius: Array    # (n,) r/cos(wall angle) [m]


def _local_wall_angle(x: Array, r: Array) -> Array:
    """Wall angle to the axis at each station, by central differences."""

    dx = jnp.gradient(x)
    dr = jnp.gradient(r)
    return jnp.arctan2(dr, jnp.where(jnp.abs(dx) < 1e-15, 1e-15, dx))


def nozzle_collapse_screen(
    grid: StationGrid,
    mission: MissionSpec,
    *,
    gas_pressure: Array,
    shell_thickness: Array,
    shell_length: Array,
) -> NozzleCollapseScreen:
    """Screen the divergent shell against external-pressure collapse.

    Parameters
    ----------
    gas_pressure
        Static wall pressure at each station [Pa].  Where the nozzle is
        overexpanded (``p_ambient > p_gas``) the wall carries net external
        pressure and can buckle inward.
    shell_thickness
        Thickness of the load-carrying shell [m].  Pass the **structural
        closeout** thickness: SP-8087 §2.1.3 puts the hoop load in the jacket,
        and crediting the land-stiffened liner/jacket sandwich requires
        SP-8007 §4.4 (isotropic sandwich cylinders), which is not implemented.
        Screening the jacket alone is therefore conservative.
    shell_length
        Unsupported shell length between stiffening rings or bands [m].  With
        no retainer bands this is the divergent length, which is the
        conservative choice.

    Returns
    -------
    NozzleCollapseScreen
        ``margin >= 0`` means the shell carries the overexpansion load with the
        configured factor of safety.

    Notes
    -----
    SP-8007 §4.2.3 gives two branches, each with its own experimentally
    recommended correlation factor ``gamma``:

    * moderate length (eq. 16, ``gamma = 0.75`` per eq. 20)::

          p_cr = 0.855 * gamma * E * (t/r)^2.5 * (r/L) / (1 - v^2)^0.75

    * long cylinder buckling into an oval, n = 2 (eq. 19, ``gamma = 0.90`` per
      eq. 21)::

          p_cr = gamma * E * (t/r)^3 / (4 (1 - v^2))

    The governing allowable is the **larger** of the two, not the smaller.
    SP-8007 figure 4 plots the buckling coefficient against the Batdorf
    parameter ``Z``: the eq. (15)/(16) straight line *falls* with increasing
    ``Z`` until it meets the oval-mode asymptote for that ``r/t``, and is flat
    beyond it.  Equation (19) is therefore the long-cylinder **floor** that a
    finite shell sits above, not a cap on it -- as ``L`` grows, ``r/L`` and
    hence eq. (16) go to zero while eq. (19) does not.  Taking the minimum
    would apply the infinite-length asymptote to a short nozzle and reject
    shells that are in fact fine; on the 13 kN baseline that error alone
    reported a -0.84 collapse margin for a shell whose true margin is positive.

    A smooth maximum is used so the mode changeover does not hand the NLP an
    active-set kink.  ``logaddexp`` sits at most ``ln 2 / k`` above the true
    maximum, i.e. under 2 % of the pressure scale here, which is small against
    the factor of safety and is documented rather than hidden.

    The divergent is a cone, not a cylinder.  The equivalent-cylinder mapping
    ``r_eq = r / cos(wall angle)`` — the radius of curvature normal to the wall
    — is applied, following the standard truncated-cone treatment; NASA SP-8019
    is the qualification path for a real conical shell.
    """

    x = grid.x
    r = grid.r
    t = jnp.asarray(shell_thickness, dtype=jnp.float64) * jnp.ones_like(r)
    L = jnp.asarray(shell_length, dtype=jnp.float64)
    E = jnp.asarray(mission.closeout_E, dtype=jnp.float64)
    nu = jnp.asarray(mission.closeout_poisson, dtype=jnp.float64)

    # Only the divergent can be overexpanded; upstream of the throat the wall
    # always sees chamber pressure.  A smooth ramp on area ratio keeps this
    # free of a design-dependent branch.
    p_gas = jnp.asarray(gas_pressure, dtype=jnp.float64)
    dp_ext = jnp.maximum(mission.Pa - p_gas, 0.0)

    # Equivalent cylinder radius for a conical shell.
    angle = _local_wall_angle(x, r)
    r_eq = r / jnp.maximum(jnp.cos(angle), 0.2)

    one_minus_nu2 = 1.0 - nu ** 2
    t_over_r = t / jnp.maximum(r_eq, 1e-12)

    p_moderate = (
        0.855 * mission.nozzle_collapse_gamma_moderate * E
        * t_over_r ** 2.5
        * (jnp.maximum(r_eq, 1e-12) / jnp.maximum(L, 1e-12))
        / one_minus_nu2 ** 0.75
    )
    p_long = (
        mission.nozzle_collapse_gamma_long * E * t_over_r ** 3
        / (4.0 * one_minus_nu2)
    )
    # Smooth maximum: eq. (19) is the long-cylinder FLOOR, not a cap.
    scale = jnp.maximum(jnp.max(p_moderate), 1.0)
    p_cr = scale * jnp.logaddexp(
        40.0 * p_moderate / scale, 40.0 * p_long / scale
    ) / 40.0

    allowable = p_cr / mission.nozzle_collapse_fos
    margin_profile = allowable - dp_ext
    margin = jnp.min(margin_profile)
    normalized = margin / jnp.maximum(jnp.max(dp_ext), 1.0)
    return NozzleCollapseScreen(
        external_dp=dp_ext,
        critical_pressure=p_cr,
        margin_profile=margin_profile,
        margin=margin,
        normalized_margin=normalized,
        equivalent_radius=r_eq,
    )
