"""Residual primitives for the Rao variational/MOC coupling."""

from __future__ import annotations

import math

import numpy as np

from raosim.gas_dynamics import prandtl_meyer
from raosim.moc import FlowNode


def _source_axisym(theta: float, mu: float, r: float) -> float:
    """Axisymmetric source magnitude S = sin(theta) sin(mu) / r (ds-form).

    Corrected 2026-06-11: the previous Q± carried a spurious
    cos(mu)/cos(theta ± mu) factor — in arc-length parametrisation the
    direction cosines cancel and the source is simply S = sinθ sinμ / r
    (Anderson, *Modern Compressible Flow* §11.4; Zucrow & Hoffman,
    *Gas Dynamics* Vol. 2 Ch. 17).  Validated against the NASA
    M3.5Perf oracle: on kernel RRC segments d(θ+ν) − S·ds has
    RMS 2.3e-6 (the old forms: 2.7e-4 / 4.9e-4); on a NASA-``Deriv``
    LRC, d(θ−ν) + S·ds has RMS 8.8e-8.
    """
    if r <= 1e-12:
        return 0.0
    return math.sin(theta) * math.sin(mu) / r


def residual_Cplus_axisym(
    p0: FlowNode,
    p1: FlowNode,
    gamma: float,
    *,
    axisymmetric: bool = True,
) -> float:
    """
    Axisymmetric C+ (left-running, slope tan(θ+μ)) compatibility
    residual from ``p0`` to ``p1`` (ordered downstream: increasing x
    along the characteristic).

    Along C+: **d(θ − ν) = −(sinθ sinμ / r) ds**.  With
    ``axisymmetric=False`` this reduces to the planar invariant check
    d(θ − ν) = 0 (K+ = θ − ν constant along C+; Anderson MCF §11.4,
    Liepmann & Roshko §4.13; Zucrow & Hoffman Vol. 2 Ch. 17).

    CORRECTED 2026-06-11: this function previously enforced
    d(θ + ν) = Q+ ds — the *C− family's* relation — along the C+ line
    (the invariant pairing was mirrored throughout the
    rao_residuals/moc/jax stack; identified by ibrahim).  Empirical
    proof against the NASA oracle: on a true LRC generated by the
    verbatim NASA ``Deriv``/``RungeKutta`` port, this form holds at
    RMS 8.8e-8 while the old pairing reads 3.4e-3.
    """
    nu0 = prandtl_meyer(max(float(p0.M), 1.001), gamma)
    nu1 = prandtl_meyer(max(float(p1.M), 1.001), gamma)
    lhs = (p1.theta - nu1) - (p0.theta - nu0)
    if not axisymmetric:
        return lhs

    ds = math.hypot(p1.x - p0.x, p1.r - p0.r)
    theta = 0.5 * (p0.theta + p1.theta)
    mu = 0.5 * (p0.mu + p1.mu)
    r = max(0.5 * (p0.r + p1.r), 1e-12)
    return lhs + _source_axisym(theta, mu, r) * ds


def residual_Cminus_axisym(
    p0: FlowNode,
    p1: FlowNode,
    gamma: float,
    *,
    axisymmetric: bool = True,
) -> float:
    """
    Axisymmetric C− (right-running, slope tan(θ−μ)) compatibility
    residual from ``p0`` to ``p1`` (ordered downstream: increasing x
    along the characteristic).

    Along C−: **d(θ + ν) = +(sinθ sinμ / r) ds**.  With
    ``axisymmetric=False`` this reduces to the planar invariant check
    d(θ + ν) = 0 (K− = θ + ν constant along C−).

    CORRECTED 2026-06-11 (see :func:`residual_Cplus_axisym`): validated
    on the M3.5Perf oracle kernel RRCs (true C− characteristics) at
    RMS 2.3e-6; the previously-enforced d(θ−ν) form reads 5.5e-3 there.
    """
    nu0 = prandtl_meyer(max(float(p0.M), 1.001), gamma)
    nu1 = prandtl_meyer(max(float(p1.M), 1.001), gamma)
    lhs = (p1.theta + nu1) - (p0.theta + nu0)
    if not axisymmetric:
        return lhs

    ds = math.hypot(p1.x - p0.x, p1.r - p0.r)
    theta = 0.5 * (p0.theta + p1.theta)
    mu = 0.5 * (p0.mu + p1.mu)
    r = max(0.5 * (p0.r + p1.r), 1e-12)
    return lhs - _source_axisym(theta, mu, r) * ds


def residual_left_mach_geometry(p0: FlowNode, p1: FlowNode) -> float:
    """Geometric residual for a left-running Mach line segment."""
    dx = p1.x - p0.x
    dr = p1.r - p0.r
    theta = 0.5 * (p0.theta + p1.theta)
    mu = 0.5 * (p0.mu + p1.mu)
    return dr - dx * math.tan(theta + mu)


def residual_wall_tangency(w0: FlowNode, w1: FlowNode) -> float:
    """Wall segment tangency residual using the average local flow angle."""
    dx = w1.x - w0.x
    dr = w1.r - w0.r
    theta = 0.5 * (w0.theta + w1.theta)
    return dr - dx * math.tan(theta)


def residual_cplus_child_position(
    parent: FlowNode,
    child: FlowNode,
) -> float:
    """
    Geometric residual: does ``child`` lie on the C+ line through ``parent``?

    Lightweight alternative to :func:`residual_intersection` for the
    Phase 6 coupled wall — wall points are streamlines fed by a single C+
    from the CE, so we only need the one geometric equation
    ``dr = tan(theta_avg + mu_avg) * dx`` rather than the two-equation
    C+/C- intersection check.
    """
    dx = child.x - parent.x
    dr = child.r - parent.r
    theta_avg = 0.5 * (parent.theta + child.theta)
    mu_avg = 0.5 * (parent.mu + child.mu)
    return dr - math.tan(theta_avg + mu_avg) * dx


def residual_intersection(
    p_plus: FlowNode,
    p_minus: FlowNode,
    child: FlowNode,
    x_scale: float,
    r_scale: float,
) -> np.ndarray:
    """
    Geometric intersection residual for a child C+/C- point.

    ``p_plus`` carries the C+ line, ``p_minus`` carries the C- line.  The
    returned two-vector is scaled in radius units so it can be stacked in
    least-squares residuals.
    """
    _ = x_scale
    scale = max(abs(r_scale), 1e-12)
    slope_p = math.tan(0.5 * (p_plus.theta + child.theta)
                       + 0.5 * (p_plus.mu + child.mu))
    slope_m = math.tan(0.5 * (p_minus.theta + child.theta)
                       - 0.5 * (p_minus.mu + child.mu))
    cplus = (child.r - p_plus.r) - slope_p * (child.x - p_plus.x)
    cminus = (child.r - p_minus.r) - slope_m * (child.x - p_minus.x)
    return np.array([cplus / scale, cminus / scale], dtype=float)
